name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  intl: ^0.20.1
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  syncfusion_flutter_charts: ^28.1.41

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.8

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: Assets

  fonts:
    enabled: true

flutter:
  uses-material-design: true

  assets:
    - "assets/animations/"
    - "assets/images/"
